using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using NagiCore.Services;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
namespace NagiCore.Modules.Billing;
public sealed class InvoiceItem { public string Description {get;set;}=""; public decimal Quantity {get;set;} public decimal UnitPrice {get;set;} public decimal TaxPercent {get;set;} public decimal Discount {get;set;} public decimal LineSubtotal => Math.Round(Math.Max(0m,Quantity)*Math.Max(0m,UnitPrice)-Math.Max(0m,Discount),2); public decimal Tax => Math.Round(LineSubtotal*Math.Max(0m,TaxPercent)/100m,2); public decimal Total => LineSubtotal+Tax; }
public sealed class Invoice { public string Id {get;set;}=Guid.NewGuid().ToString("N"); public string InvoiceNumber {get;set;}=""; public DateTime Date {get;set;}=DateTime.Now; public string CustomerName {get;set;}=""; public string CustomerPhone {get;set;}=""; public string CustomerAddress {get;set;}=""; public string PaymentStatus {get;set;}="Pending"; public List<InvoiceItem> Items {get;set;}=new List<InvoiceItem>(); public decimal Subtotal=>Math.Round(Items.Sum(x=>x.LineSubtotal),2); public decimal Tax=>Math.Round(Items.Sum(x=>x.Tax),2); public decimal Discount=>Math.Round(Items.Sum(x=>Math.Max(0m,x.Discount)),2); public decimal Total=>Math.Round(Items.Sum(x=>x.Total),2); }
public sealed class InvoiceDatabase { public List<Invoice> Invoices {get;set;}=new List<Invoice>(); }
public sealed class BillingModule {
 readonly JsonDataStore<InvoiceDatabase> store=new JsonDataStore<InvoiceDatabase>("billing.json");
 public string Name=>"Billing"; public string Description=>"Accurate invoices, taxes, payments, history and exports.";
 public List<Invoice> List(string q=null){var d=store.Load().Invoices;if(string.IsNullOrWhiteSpace(q))return d.OrderByDescending(x=>x.Date).ToList();q=q.Trim();return d.Where(x=>x.InvoiceNumber.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0||x.CustomerName.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0).OrderByDescending(x=>x.Date).ToList();}
 public Invoice Create(string customer,string phone,string address,IEnumerable<InvoiceItem> items,string status){if(string.IsNullOrWhiteSpace(customer))throw new ArgumentException("Customer name is required.");var list=items==null?new List<InvoiceItem>():items.ToList();if(list.Count==0)throw new ArgumentException("At least one item is required.");foreach(var i in list)if(i.Quantity<=0||i.UnitPrice<0||i.TaxPercent<0||i.Discount<0)throw new ArgumentException("Invoice item values are invalid.");var db=store.Load();var n="INV-"+DateTime.Now.ToString("yyyyMMdd-HHmmss",CultureInfo.InvariantCulture);while(db.Invoices.Any(x=>x.InvoiceNumber==n))n+="1";var inv=new Invoice{InvoiceNumber=n,CustomerName=customer.Trim(),CustomerPhone=phone?.Trim()??"",CustomerAddress=address?.Trim()??"",PaymentStatus=string.IsNullOrWhiteSpace(status)?"Pending":status.Trim(),Items=list};db.Invoices.Add(inv);store.Save(db);return inv;}
 public void Update(Invoice invoice){if(invoice==null)throw new ArgumentNullException(nameof(invoice));if(string.IsNullOrWhiteSpace(invoice.CustomerName))throw new ArgumentException("Customer name is required.");if(invoice.Items==null||invoice.Items.Count==0)throw new ArgumentException("At least one invoice item is required.");foreach(var i in invoice.Items)if(i.Quantity<=0||i.UnitPrice<0||i.TaxPercent<0||i.Discount<0)throw new ArgumentException("Invoice item values are invalid.");var db=store.Load();var old=db.Invoices.FirstOrDefault(x=>x.Id==invoice.Id);if(old==null)throw new InvalidOperationException("Invoice was not found.");var index=db.Invoices.IndexOf(old);db.Invoices[index]=invoice;store.Save(db);}\n public void Delete(string id){var db=store.Load();db.Invoices.RemoveAll(x=>x.Id==id);store.Save(db);}
 public void ExportCsv(string path){using(var w=new StreamWriter(path,false,new UTF8Encoding(true))){w.WriteLine("Invoice,Date,Customer,Phone,PaymentStatus,Subtotal,Tax,Discount,Total");foreach(var i in List())w.WriteLine(string.Join(",",Csv(i.InvoiceNumber),i.Date.ToString("s"),Csv(i.CustomerName),Csv(i.CustomerPhone),Csv(i.PaymentStatus),i.Subtotal.ToString("0.00"),i.Tax.ToString("0.00"),i.Discount.ToString("0.00"),i.Total.ToString("0.00")));}}
 public void ExportPdf(Invoice inv,string path,string businessName="NagiCore"){if(inv==null)throw new ArgumentNullException(nameof(inv));var doc=new PdfDocument();var page=doc.AddPage();var g=XGraphics.FromPdfPage(page);var title=new XFont("Arial",18,XFontStyle.Bold);var normal=new XFont("Arial",9,XFontStyle.Regular);g.DrawString(businessName,title,XBrushes.Black,40,45);g.DrawString("Invoice "+inv.InvoiceNumber,normal,XBrushes.Black,40,65);g.DrawString("Date: "+inv.Date.ToString("dd MMM yyyy HH:mm"),normal,XBrushes.Black,40,82);g.DrawString("Customer: "+inv.CustomerName,normal,XBrushes.Black,40,100);g.DrawString("Payment: "+inv.PaymentStatus,normal,XBrushes.Black,40,118);double y=150;foreach(var i in inv.Items){g.DrawString(i.Description,normal,XBrushes.Black,40,y);g.DrawString(i.Quantity.ToString("0.##"),normal,XBrushes.Black,300,y);g.DrawString(i.UnitPrice.ToString("0.00"),normal,XBrushes.Black,360,y);g.DrawString(i.Total.ToString("0.00"),normal,XBrushes.Black,450,y);y+=18;}g.DrawString("Subtotal: "+inv.Subtotal.ToString("0.00"),normal,XBrushes.Black,360,y+20);g.DrawString("Tax: "+inv.Tax.ToString("0.00"),normal,XBrushes.Black,360,y+38);g.DrawString("Discount: "+inv.Discount.ToString("0.00"),normal,XBrushes.Black,360,y+56);g.DrawString("TOTAL: "+inv.Total.ToString("0.00"),title,XBrushes.Black,360,y+78);doc.Save(path);}
 static string Csv(string s){var q=((char)34).ToString();return q+(s??"").Replace(q,q+q)+q;}
}